-- MISE-005HC: pin public.supplier_orders.order_message to reject unsafe
-- control characters under COLLATE "C", while allowing multiline bodies.
--
-- supplier_orders_message_size_check only enforced
-- `octet_length(order_message) <= 65536`. It had no control-character gate.
-- supplier_orders_operational_values_check already requires
-- length(trim(order_message)) > 0 alongside non-empty supplier_name and is
-- left intact so this tip stays alone-OK versus open supplier_name (#612)
-- and operator_note (#551) pins. Bare POSIX [[:cntrl:]] would also reject
-- LF (and the supplier-send multiline allowlist), so this tip uses the same
-- byte class as services/miseValidation.ts
-- `unsafeSupplierSendMultilineControlPattern`:
--   reject U+0000–U+0008, U+000B, U+000C, U+000E–U+001F, U+007F
--   allow LF (U+000A), and also TAB (U+0009) / CR (U+000D) for parity
--   with the established supplier-send multiline control pattern.
--
-- order_message is the durable NOT NULL supplier-send body that is
-- regenerated by private.build_supplier_order_message, previewed/approved
-- under MISE-003B, and delivered as email body content. Legitimate bodies
-- contain intentional newlines (line lists and Notes blocks). If LC_CTYPE
-- drifted under a bare (or missing) cntrl gate, dump/restore could accept
-- body bytes a restored C-locale path would refuse — or the reverse —
-- breaking order-content continuity and send-fingerprint parity across
-- restore.
--
-- Scope:
--   - Reattach supplier_orders_message_size_check preserving the exact
--     octet_length <= 65536 bound PLUS multiline-aware ASCII control
--     rejection under COLLATE "C"
--   - Column is NOT NULL; no null OR branch
-- Does NOT rewrite supplier-send builders, draft-update RPCs,
-- supplier_orders_operational_values_check, operator_note (#551),
-- supplier_name (#612), or provider_message_id (#445).
-- Timestamp after MISE-005HB (#618).

alter table public.supplier_orders
  drop constraint if exists supplier_orders_message_size_check;

alter table public.supplier_orders
  add constraint supplier_orders_message_size_check check (
    octet_length(order_message) <= 65536
    and order_message collate "C" !~ E'[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]'
  );

comment on constraint supplier_orders_message_size_check on public.supplier_orders is
  'MISE-005HC: order_message octet_length <= 65536 plus multiline-aware ASCII control rejection under COLLATE "C" (allows LF/TAB/CR; rejects other C0 controls and DEL).';
