-- MISE-004A: append-only purchase decision evidence and deterministic patterns.
-- This is bounded decision memory, not recommendation authority. Patterns are
-- computed on read and are not consumed by the recommendation engine.

create table public.purchase_decision_events (
  id uuid primary key default gen_random_uuid(),
  sequence bigint generated by default as identity unique,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text not null check (actor_role in ('owner', 'admin', 'manager')),
  decision_type text not null check (
    decision_type in (
      'approve', 'approve_with_override', 'dismiss', 'undo',
      'exclude_from_learning'
    )
  ),
  purchase_recommendation_id uuid not null,
  inventory_item_id uuid not null,
  supplier_id uuid not null,
  recommendation_source text not null check (
    recommendation_source in ('mise_rules', 'legacy_client')
  ),
  recommendation_unit text not null check (
    length(trim(recommendation_unit)) between 1 and 80
    and recommendation_unit !~ '[[:cntrl:]]'
  ),
  recommended_quantity numeric not null check (
    recommended_quantity > 0 and recommended_quantity <= 1000000000
  ),
  chosen_quantity numeric check (
    chosen_quantity is null or (chosen_quantity > 0 and chosen_quantity <= 1000000000)
  ),
  canonical_unit text not null check (canonical_unit in ('g', 'ml', 'each')),
  canonical_quantity_per_unit numeric not null check (
    canonical_quantity_per_unit > 0 and canonical_quantity_per_unit <= 1000000000
  ),
  recommended_canonical_quantity numeric not null check (
    recommended_canonical_quantity > 0
    and recommended_canonical_quantity <= 1000000000000000000
  ),
  chosen_canonical_quantity numeric check (
    chosen_canonical_quantity is null
    or (
      chosen_canonical_quantity > 0
      and chosen_canonical_quantity <= 1000000000000000000
    )
  ),
  quantity_delta numeric,
  canonical_quantity_delta numeric generated always as (
    chosen_canonical_quantity - recommended_canonical_quantity
  ) stored,
  quantity_ratio numeric check (
    quantity_ratio is null or (quantity_ratio > 0 and quantity_ratio <= 1000000000)
  ),
  planning_revision bigint check (planning_revision is null or planning_revision >= 0),
  context_evidence jsonb not null default '{}'::jsonb check (
    jsonb_typeof(context_evidence) = 'object'
    and pg_column_size(context_evidence) <= 8192
  ),
  target_event_id uuid,
  source_audit_log_id uuid,
  source_event_key text not null check (length(source_event_key) between 8 and 200),
  evidence_version text not null default 'mise.purchase_decision.v1'
    check (evidence_version = 'mise.purchase_decision.v1'),
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint purchase_decision_events_restaurant_id_id_key unique (restaurant_id, id),
  constraint purchase_decision_events_source_key unique (restaurant_id, source_event_key),
  constraint purchase_decision_events_target_fk foreign key (restaurant_id, target_event_id)
    references public.purchase_decision_events(restaurant_id, id),
  constraint purchase_decision_events_shape_check check (
    (
      decision_type = 'approve'
      and target_event_id is null
      and chosen_quantity = recommended_quantity
      and chosen_canonical_quantity = recommended_canonical_quantity
      and quantity_delta = 0
      and canonical_quantity_delta = 0
      and quantity_ratio = 1
    )
    or (
      decision_type = 'approve_with_override'
      and target_event_id is null
      and chosen_quantity is not null
      and chosen_quantity <> recommended_quantity
      and chosen_canonical_quantity is not null
      and quantity_delta = chosen_quantity - recommended_quantity
      and canonical_quantity_delta = chosen_canonical_quantity - recommended_canonical_quantity
      and quantity_ratio = chosen_quantity / recommended_quantity
    )
    or (
      decision_type = 'dismiss'
      and target_event_id is null
      and chosen_quantity is null
      and chosen_canonical_quantity is null
      and quantity_delta is null
      and canonical_quantity_delta is null
      and quantity_ratio is null
    )
    or (
      decision_type in ('undo', 'exclude_from_learning')
      and target_event_id is not null
    )
  )
);

create index purchase_decision_events_pattern_idx
on public.purchase_decision_events (
  restaurant_id, inventory_item_id, supplier_id, canonical_unit,
  recommendation_source, occurred_at desc
);
create index purchase_decision_events_recommendation_idx
on public.purchase_decision_events (
  restaurant_id, purchase_recommendation_id, sequence desc
);
create index purchase_decision_events_target_idx
on public.purchase_decision_events (restaurant_id, target_event_id)
where target_event_id is not null;
create unique index purchase_decision_events_one_undo_idx
on public.purchase_decision_events (restaurant_id, target_event_id)
where decision_type = 'undo';
create unique index purchase_decision_events_one_exclusion_idx
on public.purchase_decision_events (restaurant_id, target_event_id)
where decision_type = 'exclude_from_learning';

comment on table public.purchase_decision_events is
  'MISE-004A immutable operator purchase decisions. It is evidence only and is not recommendation authority.';
comment on column public.purchase_decision_events.context_evidence is
  'Bounded allowlisted action-time context. Raw provider payloads, notes, message bodies, and email content are prohibited.';

alter table public.purchase_decision_events enable row level security;
revoke all on table public.purchase_decision_events from public, anon, authenticated;
revoke all on sequence public.purchase_decision_events_sequence_seq
from public, anon, authenticated;
grant select on table public.purchase_decision_events to service_role;

create or replace function private.reject_purchase_decision_event_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE'
    and pg_catalog.current_setting('mise.inventory_event_tenant_delete', true) = 'true'
  then
    return old;
  end if;

  if tg_op = 'UPDATE'
    and old.actor_user_id is not null
    and new.actor_user_id is null
    and not exists (
      select 1 from auth.users auth_user where auth_user.id = old.actor_user_id
    )
    and (pg_catalog.to_jsonb(new) - 'actor_user_id')
      is not distinct from (pg_catalog.to_jsonb(old) - 'actor_user_id')
  then
    return new;
  end if;

  raise exception 'Purchase decision events are append-only' using errcode = '55000';
end;
$$;

revoke all on function private.reject_purchase_decision_event_mutation()
from public, anon, authenticated, service_role;

create trigger reject_purchase_decision_event_update_delete
before update or delete on public.purchase_decision_events
for each row execute function private.reject_purchase_decision_event_mutation();

create or replace function private.purchase_decision_actor_role(p_restaurant_id uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select membership.role
  from public.restaurant_memberships membership
  where membership.restaurant_id = p_restaurant_id
    and membership.user_id = auth.uid()
    and membership.status = 'active'
    and membership.role in ('owner', 'admin', 'manager')
  limit 1
$$;

create or replace function private.purchase_decision_context(
  p_authority jsonb,
  p_planning_revision bigint
)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
    'planningRevision', coalesce(
      case when pg_catalog.jsonb_typeof(p_authority->'planningRevision') = 'number'
        then p_authority->'planningRevision' end,
      pg_catalog.to_jsonb(p_planning_revision)
    ),
    'authorityEvaluatedAt', p_authority->'evaluatedAt',
    'countEventId', p_authority#>'{evidence,countEventId}',
    'countedAt', p_authority#>'{evidence,countedAt}',
    'projectedQuantity', p_authority#>'{evidence,projectedQuantity}',
    'providerWindowFrom', p_authority#>'{evidence,providerWindowFrom}',
    'providerWindowTo', p_authority#>'{evidence,providerWindowTo}',
    'providerWindowCompletedAt', p_authority#>'{evidence,providerWindowCompletedAt}',
    'demandBasis', p_authority#>'{evidence,demandBasis}',
    'basis', p_authority#>'{evidence,basis}',
    'hasRecipeRevisions', case
      when pg_catalog.jsonb_typeof(p_authority#>'{evidence,recipeRevisions}') = 'object'
      then pg_catalog.to_jsonb(
        (p_authority#>'{evidence,recipeRevisions}') <> '{}'::jsonb
      ) end
  ))
$$;

create or replace function private.record_purchase_decision_base_event(
  p_recommendation public.purchase_recommendations,
  p_decision text,
  p_recommended_quantity numeric,
  p_chosen_quantity numeric,
  p_authority jsonb,
  p_source_audit_log_id uuid,
  p_occurred_at timestamptz
)
returns public.purchase_decision_events
language plpgsql
security definer
set search_path = ''
as $$
declare
  item public.inventory_items%rowtype;
  actor_role text;
  decision_type text;
  event_row public.purchase_decision_events%rowtype;
  factor numeric;
begin
  if p_recommendation.generation_source not in ('mise_rules', 'legacy_client') then
    raise exception 'Only Mise-generated recommendations produce purchase memory evidence'
      using errcode = '22023';
  end if;
  actor_role := private.purchase_decision_actor_role(p_recommendation.restaurant_id);
  if actor_role is null or auth.uid() is null then
    raise exception 'Manager access required' using errcode = '42501';
  end if;
  select * into item from public.inventory_items candidate
  where candidate.restaurant_id = p_recommendation.restaurant_id
    and candidate.id = p_recommendation.inventory_item_id
    and candidate.supplier_id = p_recommendation.supplier_id
  for share;
  if not found
    or item.canonical_unit_verification_status <> 'verified'
    or item.canonical_unit is null
    or item.canonical_quantity_per_unit is null
  then
    raise exception 'Verified canonical purchase evidence is required'
      using errcode = '55000';
  end if;
  if p_source_audit_log_id is null then
    raise exception 'Purchase decision audit identity is required' using errcode = '55000';
  end if;
  factor := item.canonical_quantity_per_unit;
  decision_type := case
    when p_decision = 'dismiss' then 'dismiss'
    when p_chosen_quantity is distinct from p_recommended_quantity
      then 'approve_with_override'
    else 'approve'
  end;
  if p_decision not in ('approve', 'dismiss') then
    raise exception 'Unsupported purchase decision type' using errcode = '22023';
  end if;

  insert into public.purchase_decision_events (
    restaurant_id, actor_user_id, actor_role, decision_type,
    purchase_recommendation_id, inventory_item_id, supplier_id,
    recommendation_source, recommendation_unit,
    recommended_quantity, chosen_quantity, canonical_unit,
    canonical_quantity_per_unit, recommended_canonical_quantity,
    chosen_canonical_quantity, quantity_delta, quantity_ratio,
    planning_revision, context_evidence, source_audit_log_id,
    source_event_key, occurred_at
  ) values (
    p_recommendation.restaurant_id, auth.uid(), actor_role, decision_type,
    p_recommendation.id, p_recommendation.inventory_item_id,
    p_recommendation.supplier_id, p_recommendation.generation_source,
    p_recommendation.unit, p_recommended_quantity,
    case when p_decision = 'dismiss' then null else p_chosen_quantity end,
    item.canonical_unit, factor, p_recommended_quantity * factor,
    case when p_decision = 'dismiss' then null else p_chosen_quantity * factor end,
    case when p_decision = 'dismiss' then null
      else p_chosen_quantity - p_recommended_quantity end,
    case when p_decision = 'dismiss' then null
      else p_chosen_quantity / p_recommended_quantity end,
    p_recommendation.planning_revision,
    private.purchase_decision_context(p_authority, p_recommendation.planning_revision),
    p_source_audit_log_id, 'audit_log:' || p_source_audit_log_id::text,
    p_occurred_at
  ) returning * into event_row;
  return event_row;
end;
$$;

create or replace function private.record_purchase_decision_compensation(
  p_target public.purchase_decision_events,
  p_decision_type text,
  p_source_audit_log_id uuid,
  p_source_event_key text,
  p_occurred_at timestamptz
)
returns public.purchase_decision_events
language plpgsql
security definer
set search_path = ''
as $$
declare
  event_row public.purchase_decision_events%rowtype;
  actor_role text;
begin
  if p_target.decision_type not in ('approve', 'approve_with_override', 'dismiss')
    or p_decision_type not in ('undo', 'exclude_from_learning')
  then
    raise exception 'Invalid purchase decision compensation' using errcode = '22023';
  end if;
  actor_role := private.purchase_decision_actor_role(p_target.restaurant_id);
  if actor_role is null or auth.uid() is null then
    raise exception 'Manager access required' using errcode = '42501';
  end if;
  insert into public.purchase_decision_events (
    restaurant_id, actor_user_id, actor_role, decision_type,
    purchase_recommendation_id, inventory_item_id, supplier_id,
    recommendation_source, recommendation_unit, recommended_quantity,
    chosen_quantity, canonical_unit, canonical_quantity_per_unit,
    recommended_canonical_quantity, chosen_canonical_quantity,
    quantity_delta, quantity_ratio, planning_revision, context_evidence,
    target_event_id, source_audit_log_id, source_event_key, occurred_at
  ) values (
    p_target.restaurant_id, auth.uid(), actor_role, p_decision_type,
    p_target.purchase_recommendation_id, p_target.inventory_item_id,
    p_target.supplier_id, p_target.recommendation_source,
    p_target.recommendation_unit, p_target.recommended_quantity,
    p_target.chosen_quantity, p_target.canonical_unit,
    p_target.canonical_quantity_per_unit, p_target.recommended_canonical_quantity,
    p_target.chosen_canonical_quantity, p_target.quantity_delta,
    p_target.quantity_ratio, p_target.planning_revision,
    p_target.context_evidence, p_target.id, p_source_audit_log_id,
    p_source_event_key, p_occurred_at
  ) returning * into event_row;
  return event_row;
end;
$$;

revoke all on function private.purchase_decision_actor_role(uuid)
from public, anon, authenticated, service_role;
revoke all on function private.purchase_decision_context(jsonb, bigint)
from public, anon, authenticated, service_role;
revoke all on function private.record_purchase_decision_base_event(
  public.purchase_recommendations, text, numeric, numeric, jsonb, uuid, timestamptz
) from public, anon, authenticated, service_role;
revoke all on function private.record_purchase_decision_compensation(
  public.purchase_decision_events, text, uuid, text, timestamptz
) from public, anon, authenticated, service_role;

-- Preserve the complete MISE-003C implementations behind private wrappers.
alter function public.approve_purchase_recommendation(uuid, uuid, numeric)
  rename to approve_purchase_recommendation_mise_003c_base;
alter function public.approve_purchase_recommendation_mise_003c_base(uuid, uuid, numeric)
  set schema private;
alter function public.dismiss_purchase_recommendation(uuid, uuid)
  rename to dismiss_purchase_recommendation_pre_mise_004a;
alter function public.dismiss_purchase_recommendation_pre_mise_004a(uuid, uuid)
  set schema private;
alter function public.undo_purchase_recommendation_action(uuid, uuid)
  rename to undo_purchase_recommendation_action_mise_003c_base;
alter function public.undo_purchase_recommendation_action_mise_003c_base(uuid, uuid)
  set schema private;

revoke all on function private.approve_purchase_recommendation_mise_003c_base(uuid, uuid, numeric)
from public, anon, authenticated, service_role;
revoke all on function private.dismiss_purchase_recommendation_pre_mise_004a(uuid, uuid)
from public, anon, authenticated, service_role;
revoke all on function private.undo_purchase_recommendation_action_mise_003c_base(uuid, uuid)
from public, anon, authenticated, service_role;

create function public.approve_purchase_recommendation(
  p_restaurant_id uuid,
  p_recommendation_id uuid,
  p_recommended_quantity numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  recommendation_prelock public.purchase_recommendations%rowtype;
  recommendation_snapshot public.purchase_recommendations%rowtype;
  result jsonb;
  audit_row public.audit_logs%rowtype;
  decision_event public.purchase_decision_events%rowtype;
  chosen_quantity numeric;
begin
  select * into recommendation_prelock
  from public.purchase_recommendations recommendation
  where recommendation.restaurant_id = p_restaurant_id
    and recommendation.id = p_recommendation_id;
  if not found then raise exception 'Recommendation not found' using errcode = 'P0002'; end if;
  perform private.lock_supplier_authority(
    p_restaurant_id, recommendation_prelock.supplier_id
  );
  select * into recommendation_snapshot
  from public.purchase_recommendations recommendation
  where recommendation.restaurant_id = p_restaurant_id
    and recommendation.id = p_recommendation_id
  for update;
  if recommendation_snapshot.supplier_id is distinct from recommendation_prelock.supplier_id then
    raise exception 'Recommendation supplier identity changed concurrently; retry'
      using errcode = '40001';
  end if;

  result := private.approve_purchase_recommendation_mise_003c_base(
    p_restaurant_id, p_recommendation_id, p_recommended_quantity
  );
  if result->>'outcome' = 'applied'
    and recommendation_snapshot.generation_source in ('mise_rules', 'legacy_client')
  then
    select * into audit_row from public.audit_logs audit
    where audit.restaurant_id = p_restaurant_id
      and audit.entity_id = p_recommendation_id
      and audit.action = 'recommendation_approved'
      and audit.actor_user_id = auth.uid()
    order by audit.created_at desc, audit.id desc limit 1;
    chosen_quantity := (result#>>'{recommendation,recommended_quantity}')::numeric;
    decision_event := private.record_purchase_decision_base_event(
      recommendation_snapshot, 'approve', recommendation_snapshot.recommended_quantity,
      chosen_quantity, result->'authority', audit_row.id, audit_row.created_at
    );
  elsif result->>'outcome' = 'already_applied'
    and recommendation_snapshot.generation_source in ('mise_rules', 'legacy_client')
  then
    select event.* into decision_event from public.purchase_decision_events event
    where event.restaurant_id = p_restaurant_id
      and event.purchase_recommendation_id = p_recommendation_id
      and event.decision_type in ('approve', 'approve_with_override')
    order by event.sequence desc limit 1;
  end if;
  if decision_event.id is not null then
    result := result || pg_catalog.jsonb_build_object(
      'purchaseDecisionEventId', decision_event.id
    );
  end if;
  return result;
end;
$$;

create function public.dismiss_purchase_recommendation(
  p_restaurant_id uuid,
  p_recommendation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  recommendation_snapshot public.purchase_recommendations%rowtype;
  result jsonb;
  audit_row public.audit_logs%rowtype;
  decision_event public.purchase_decision_events%rowtype;
begin
  select * into recommendation_snapshot
  from public.purchase_recommendations recommendation
  where recommendation.restaurant_id = p_restaurant_id
    and recommendation.id = p_recommendation_id
  for update;
  if not found then raise exception 'Recommendation not found' using errcode = 'P0002'; end if;
  result := private.dismiss_purchase_recommendation_pre_mise_004a(
    p_restaurant_id, p_recommendation_id
  );
  if result->>'outcome' = 'applied'
    and recommendation_snapshot.generation_source in ('mise_rules', 'legacy_client')
  then
    select * into audit_row from public.audit_logs audit
    where audit.restaurant_id = p_restaurant_id
      and audit.entity_id = p_recommendation_id
      and audit.action = 'recommendation_dismissed'
      and audit.actor_user_id = auth.uid()
    order by audit.created_at desc, audit.id desc limit 1;
    decision_event := private.record_purchase_decision_base_event(
      recommendation_snapshot, 'dismiss', recommendation_snapshot.recommended_quantity,
      null, null, audit_row.id, audit_row.created_at
    );
  elsif result->>'outcome' = 'already_applied'
    and recommendation_snapshot.generation_source in ('mise_rules', 'legacy_client')
  then
    select event.* into decision_event from public.purchase_decision_events event
    where event.restaurant_id = p_restaurant_id
      and event.purchase_recommendation_id = p_recommendation_id
      and event.decision_type = 'dismiss'
    order by event.sequence desc limit 1;
  end if;
  if decision_event.id is not null then
    result := result || pg_catalog.jsonb_build_object(
      'purchaseDecisionEventId', decision_event.id
    );
  end if;
  return result;
end;
$$;

create function public.undo_purchase_recommendation_action(
  p_restaurant_id uuid,
  p_recommendation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
  audit_row public.audit_logs%rowtype;
  target public.purchase_decision_events%rowtype;
begin
  result := private.undo_purchase_recommendation_action_mise_003c_base(
    p_restaurant_id, p_recommendation_id
  );
  if result->>'outcome' = 'applied' then
    select event.* into target from public.purchase_decision_events event
    where event.restaurant_id = p_restaurant_id
      and event.purchase_recommendation_id = p_recommendation_id
      and (
        (result->>'previous_status' = 'approved'
          and event.decision_type in ('approve', 'approve_with_override'))
        or (result->>'previous_status' = 'dismissed' and event.decision_type = 'dismiss')
      )
      and not exists (
        select 1 from public.purchase_decision_events compensation
        where compensation.restaurant_id = event.restaurant_id
          and compensation.target_event_id = event.id
          and compensation.decision_type = 'undo'
      )
    order by event.sequence desc limit 1;
    if target.id is not null then
      select * into audit_row from public.audit_logs audit
      where audit.restaurant_id = p_restaurant_id
        and audit.entity_id = p_recommendation_id
        and audit.action = 'recommendation_undo'
        and audit.actor_user_id = auth.uid()
      order by audit.created_at desc, audit.id desc limit 1;
      perform private.record_purchase_decision_compensation(
        target, 'undo', audit_row.id, 'audit_log:' || audit_row.id::text,
        audit_row.created_at
      );
    end if;
  end if;
  return result;
end;
$$;

revoke all on function public.approve_purchase_recommendation(uuid, uuid, numeric)
from public, anon, authenticated, service_role;
grant execute on function public.approve_purchase_recommendation(uuid, uuid, numeric)
to authenticated;
revoke all on function public.dismiss_purchase_recommendation(uuid, uuid)
from public, anon, authenticated, service_role;
grant execute on function public.dismiss_purchase_recommendation(uuid, uuid)
to authenticated;
revoke all on function public.undo_purchase_recommendation_action(uuid, uuid)
from public, anon, authenticated, service_role;
grant execute on function public.undo_purchase_recommendation_action(uuid, uuid)
to authenticated;

create function public.exclude_purchase_decision_event(
  p_restaurant_id uuid,
  p_event_id uuid
)
returns public.purchase_decision_events
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.purchase_decision_events%rowtype;
  existing public.purchase_decision_events%rowtype;
  audit_id uuid;
  audit_time timestamptz;
begin
  if auth.uid() is null or not private.has_restaurant_role(
    p_restaurant_id, array['owner', 'admin', 'manager']
  ) then
    raise exception 'Manager access required' using errcode = '42501';
  end if;
  select * into target from public.purchase_decision_events event
  where event.restaurant_id = p_restaurant_id and event.id = p_event_id
  for update;
  if not found or target.decision_type not in ('approve', 'approve_with_override', 'dismiss') then
    raise exception 'Purchase decision event not found' using errcode = 'P0002';
  end if;
  select * into existing from public.purchase_decision_events event
  where event.restaurant_id = p_restaurant_id
    and event.target_event_id = target.id
    and event.decision_type = 'exclude_from_learning';
  if found then return existing; end if;

  audit_id := gen_random_uuid();
  audit_time := pg_catalog.clock_timestamp();
  insert into public.audit_logs (
    id, restaurant_id, actor_user_id, action, entity_table, entity_id, metadata, created_at
  ) values (
    audit_id, p_restaurant_id, auth.uid(), 'purchase_decision_excluded_from_learning',
    'purchase_decision_events', target.id,
    pg_catalog.jsonb_build_object(
      'target_event_id', target.id,
      'purchase_recommendation_id', target.purchase_recommendation_id
    ), audit_time
  );
  return private.record_purchase_decision_compensation(
    target, 'exclude_from_learning', audit_id,
    'purchase_decision_exclusion:' || target.id::text, audit_time
  );
end;
$$;

revoke all on function public.exclude_purchase_decision_event(uuid, uuid)
from public, anon, authenticated, service_role;
grant execute on function public.exclude_purchase_decision_event(uuid, uuid)
to authenticated;

-- Policy constants are deliberately centralized here and mirrored in the pure
-- demo/domain implementation: five comparable active decisions and 80% agreement.
create function public.list_purchase_decision_patterns(p_restaurant_id uuid)
returns table (
  pattern_version text,
  inventory_item_id uuid,
  supplier_id uuid,
  canonical_unit text,
  recommendation_source text,
  sample_count bigint,
  approval_count bigint,
  exact_approval_count bigint,
  override_count bigint,
  upward_override_count bigint,
  downward_override_count bigint,
  dismissal_count bigint,
  approval_rate numeric,
  dismissal_rate numeric,
  median_quantity_ratio numeric,
  median_quantity_delta numeric,
  recent_sample_count bigint,
  first_decision_at timestamptz,
  last_decision_at timestamptz,
  evidence_event_ids uuid[],
  eligible boolean,
  evidence_strength text,
  dominant_outcome text,
  current_context boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with active_events as (
    select event.*,
      case
        when event.decision_type = 'approve' then 'exact'
        when event.decision_type = 'dismiss' then 'dismiss'
        when event.quantity_ratio > 1 then 'upward'
        else 'downward'
      end as outcome_bucket
    from public.purchase_decision_events event
    where event.restaurant_id = p_restaurant_id
      and event.decision_type in ('approve', 'approve_with_override', 'dismiss')
      and not exists (
        select 1 from public.purchase_decision_events compensation
        where compensation.restaurant_id = event.restaurant_id
          and compensation.target_event_id = event.id
          and compensation.decision_type in ('undo', 'exclude_from_learning')
      )
  ), grouped as (
    select event.inventory_item_id, event.supplier_id, event.canonical_unit,
      event.recommendation_source,
      count(*) as sample_count,
      count(*) filter (where event.decision_type in ('approve', 'approve_with_override')) as approval_count,
      count(*) filter (where event.outcome_bucket = 'exact') as exact_approval_count,
      count(*) filter (where event.decision_type = 'approve_with_override') as override_count,
      count(*) filter (where event.outcome_bucket = 'upward') as upward_override_count,
      count(*) filter (where event.outcome_bucket = 'downward') as downward_override_count,
      count(*) filter (where event.outcome_bucket = 'dismiss') as dismissal_count,
      percentile_cont(0.5) within group (order by event.quantity_ratio)
        filter (where event.quantity_ratio is not null) as median_quantity_ratio,
      percentile_cont(0.5) within group (order by event.canonical_quantity_delta)
        filter (where event.canonical_quantity_delta is not null) as median_quantity_delta,
      count(*) filter (where event.occurred_at >= now() - interval '90 days') as recent_sample_count,
      min(event.occurred_at) as first_decision_at,
      max(event.occurred_at) as last_decision_at
    from active_events event
    group by event.inventory_item_id, event.supplier_id, event.canonical_unit,
      event.recommendation_source
  )
  select 'mise.purchase_pattern.v1'::text,
    grouped.inventory_item_id, grouped.supplier_id, grouped.canonical_unit,
    grouped.recommendation_source, grouped.sample_count,
    grouped.approval_count, grouped.exact_approval_count, grouped.override_count,
    grouped.upward_override_count, grouped.downward_override_count,
    grouped.dismissal_count,
    grouped.approval_count::numeric / grouped.sample_count,
    grouped.dismissal_count::numeric / grouped.sample_count,
    grouped.median_quantity_ratio::numeric,
    grouped.median_quantity_delta::numeric,
    grouped.recent_sample_count, grouped.first_decision_at, grouped.last_decision_at,
    evidence.ids, grouped.sample_count >= 5,
    case
      when grouped.sample_count < 5 then 'insufficient'
      when greatest(
        grouped.exact_approval_count, grouped.upward_override_count,
        grouped.downward_override_count, grouped.dismissal_count
      )::numeric / grouped.sample_count >= 0.8 then 'established'
      else 'emerging'
    end,
    case
      when greatest(
        grouped.exact_approval_count, grouped.upward_override_count,
        grouped.downward_override_count, grouped.dismissal_count
      )::numeric / grouped.sample_count < 0.8 then 'mixed'
      when grouped.exact_approval_count = greatest(
        grouped.exact_approval_count, grouped.upward_override_count,
        grouped.downward_override_count, grouped.dismissal_count
      ) then 'exact'
      when grouped.upward_override_count = greatest(
        grouped.exact_approval_count, grouped.upward_override_count,
        grouped.downward_override_count, grouped.dismissal_count
      ) then 'upward'
      when grouped.downward_override_count = greatest(
        grouped.exact_approval_count, grouped.upward_override_count,
        grouped.downward_override_count, grouped.dismissal_count
      ) then 'downward'
      else 'dismiss'
    end,
    exists (
      select 1 from public.inventory_items item
      where item.restaurant_id = p_restaurant_id
        and item.id = grouped.inventory_item_id
        and item.supplier_id = grouped.supplier_id
        and item.canonical_unit = grouped.canonical_unit
        and item.canonical_unit_verification_status = 'verified'
    )
  from grouped
  cross join lateral (
    select array_agg(recent.id order by recent.occurred_at desc, recent.sequence desc) as ids
    from (
      select event.id, event.occurred_at, event.sequence
      from active_events event
      where event.inventory_item_id = grouped.inventory_item_id
        and event.supplier_id = grouped.supplier_id
        and event.canonical_unit = grouped.canonical_unit
        and event.recommendation_source = grouped.recommendation_source
      order by event.occurred_at desc, event.sequence desc limit 20
    ) recent
  ) evidence
  where auth.uid() is not null
    and private.is_restaurant_member(p_restaurant_id)
  order by grouped.last_decision_at desc, grouped.inventory_item_id, grouped.supplier_id
$$;

revoke all on function public.list_purchase_decision_patterns(uuid)
from public, anon, authenticated, service_role;
grant execute on function public.list_purchase_decision_patterns(uuid)
to authenticated;

comment on function public.list_purchase_decision_patterns(uuid) is
  'Returns factual, deterministic MISE-004A aggregates. It does not alter or authorize recommendations.';
